def get_month(month):
    if (month == 1): return "January"
    if (month == 2): return "February"
    if (month == 3): return "March"
    if (month == 4): return "April"
    if (month == 5): return "May"
    if (month == 6): return "June"
    if (month == 7): return "July"
    if (month == 8): return "Augest"
    if (month == 9): return "September"
    if (month == 10): return "October"
    if (month == 11): return "November"
    if (month == 12): return "December"

def get_weekday(weekday):
    if (weekday == 0): return "Sunday"
    if (weekday == 1): return "Monday"
    if (weekday == 2): return "Tuesday"
    if (weekday == 3): return "Wednesday"
    if (weekday == 4): return "Thursday"
    if (weekday == 5): return "Friday"
    if (weekday == 6): return "Saturday"
